title: Isard VDI
description: VDI deployment based on KVM Linux. Users create and share desktops with any OS and software through templating in seconds.The Isard engine orchestrates hypervisors and focuses on optimizing desktop virtualization performance.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
